/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import static java.time.Clock.system;
import nz.ac.aut.ense701.gameModel.Game;
import nz.ac.aut.ense701.gameModel.GameState;

/**
 *
 * @author dyd2298
 */
public class LostRestartExit extends javax.swing.JFrame {

    private Game game;
    private GameState GameState;
    private MainPage MainPage;

    /**
     * Creates new form LostRestartExit
     */
    public LostRestartExit(Game game) {

        initComponents();
        this.setLocationRelativeTo(null);
        // this.pack();
        this.setSize(505, 380);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setVisible(true);
        this.game = game;
        this.GameState = game.getState();
        setVisible(true);
        writeMessage();
    }

    private void writeMessage() {
        if (GameState == GameState.LOST) {

            displayMessage.setText(game.getPlayerName() + " " + game.getLoseMessage());
            displayMessage.setForeground(new java.awt.Color(0, 0, 0));
            displayMessage.setFont(new java.awt.Font("serif", 1, 12));
            displayMessage.setOpaque(false);

        } else if (GameState == GameState.WON) {
            displayMessage.setText(game.getPlayerName() + " " + game.getWinMessage());
            displayMessage.setForeground(new java.awt.Color(0, 0, 0));
            displayMessage.setFont(new java.awt.Font("serif", 1, 12));
            displayMessage.setOpaque(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainPageButton = new javax.swing.JButton();
        RestartButton = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        displayMessage = new javax.swing.JLabel();
        NewGame = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MainPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/Main Page.png"))); // NOI18N
        MainPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainPageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(MainPageButton);
        MainPageButton.setBounds(140, 140, 223, 46);

        RestartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/Restart.png"))); // NOI18N
        RestartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(RestartButton);
        RestartButton.setBounds(140, 190, 220, 37);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/New Exit.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(140, 270, 220, 38);
        getContentPane().add(displayMessage);
        displayMessage.setBounds(50, 80, 410, 54);

        NewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon/New Game.png"))); // NOI18N
        NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameActionPerformed(evt);
            }
        });
        getContentPane().add(NewGame);
        NewGame.setBounds(140, 230, 220, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background/End_Screen.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 510, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainPageButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();

        MainPage = new MainPage(game.getPlayerName());

    }//GEN-LAST:event_MainPageButtonActionPerformed

    private void RestartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartButtonActionPerformed
        // TODO add your handling code here:
        String player = game.getPlayerName();
        game = new Game(player, "1");
        // create the GUI for the game
        final KiwiCountUI gui = new KiwiCountUI(game);
        gui.requestFocus();
        // make the GUI visible
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                gui.setVisible(true);
            }
        });
    }//GEN-LAST:event_RestartButtonActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(2);
    }//GEN-LAST:event_ExitActionPerformed

    private void NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameActionPerformed
        // TODO add your handling code here:

        String player = game.getPlayerName();

        // create the GUI for the game
        new StartPage(player);


    }//GEN-LAST:event_NewGameActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton MainPageButton;
    private javax.swing.JButton NewGame;
    private javax.swing.JButton RestartButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel displayMessage;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
